python -m IPython -i data.py \
-- \
--seed 12345 \
--tokenizer_model "google/gemma-2-2b-it" \
--max_seq_length 512 \
--halomi_repo_id "leobianco/halomi" \
--halomi_processed_repo_id "leobianco/halomi_processed" \
--rm_halomi_processed_repo_id "leobianco/rm_halomi_processed" \
--rm_validation_size 0.2 \
--writer_sft_halomi_processed_repo_id "leobianco/writer_sft_halomi_processed" \
--perl_data_repo_id "okezieowen/english_to_spanish" \
--perl_data_processed_repo_id "leobianco/perl_halomi_processed" \
--perl_train_size 1000 \
--perl_validation_size 500 \
