accelerate launch \
--config_file=/home/leobianco/.cache/huggingface/accelerate/zero3.yaml \
writer_sft.py \
-- \
--report_to "wandb" \
--run_name "writer_sft" \
--logging_steps 10 \
--output_dir ./checkpoints/halomi/writer_sft/ \
--overwrite_output_dir True \
--push_to_hub True \
--hub_model_id "leobianco/halomi_writer_sft" \
--seed 130104 \
--dataset_name "leobianco/writer_sft_halomi_processed" \
--model_identifier "google/gemma-2-2b-it" \
--do_train True \
--save_strategy "no" \
--num_train_epochs 5 \
--learning_rate 1e-4 \
--weight_decay 0.0 \
--max_seq_length 512 \
--dataset_text_field "prompt" \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 1 \
--do_eval False \
--eval_strategy "no" \
--per_device_eval_batch_size 1 \
--eval_accumulation_steps 1 \
--task_type "CAUSAL_LM" \
--r 4 \
